version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: basededatos
      POSTGRES_USER: testuser       # <--- Cambia a 'testuser'
      POSTGRES_PASSWORD: testpass   # <--- Cambia a 'testpass'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: